services:
  cm13-bot:
    build: 
      context: .
    restart: always
    environment:
      #- CM13_BOT_OWNERS
      #- CM13_BOT_REDIS_URL
      #- CM13_BOT_GAME_AUTH_TOKEN
      #- CM13_BOT_GAME_SOURCE
      #- CM13_BOT_GAME_MAIN_INSTANCE
      #- CM13_BOT_GAME_SERVER_HOST
      #- CM13_BOT_GAME_SERVER_PORT
      #- CM13_BOT_DISCORD_TOKEN
      #- CM13_BOT_DISCORD_GUILD
      #- CM13_BOT_DISCORD_GUILD_CERT_CHANNEL
      #- CM13_BOT_DISCORD_GUILD_JOIN_CHANNEL
      #- CM13_BOT_DISCORD_GUILD_TICKET_CHANNEL
      #- CM13_BOT_DISCORD_GUILD_MOD_CHANNEL
      #- CM13_BOT_DISCORD_GUILD_ADMIN_CHANNEL
      #- CM13_BOT_DISCORD_GUILD_LOG_CHANNEL
      #- CM13_BOT_DISCORD_GUILD_TALK_CHANNEL
      #- CM13_BOT_DISCORD_GUILD_TOGGLE_ROLE
      #- CM13_BOT_DISCORD_GUILD_CERTIFIED_ROLE
      #- CM13_BOT_DISCORD_GUILD_VERIFIED_ROLE
      #- CM13_BOT_DISCORD_GUILD_WAITING_ROLE
      #- CM13_BOT_DISCORD_GUILD_SYNTHETIC_ROLE
      #- CM13_BOT_DISCORD_GUILD_YAUTJA_ROLE
      #- CM13_BOT_DISCORD_GUILD_COMMANDER_ROLE
      #- CM13_BOT_DISCORD_WEBHOOK_PROFILE_PICTURE
      #- CM13_BOT_DISCORD_WEBHOOK_NAME
      #- CM13_BOT_DISCORD_COMMAND_CERTIFY_ID